
name: github action demo pipeline

on:
  push:
    branches:
      - main

jobs:
  extract-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show Python version
        run: python --version

      - name: installing dependencies
        run: pip install pandas
      - name: run python program
        run: python extract_data.py